name: Destroy Preview Environment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install vCluster CLI
        uses: loft-sh/setup-loft@v2
        with:
          version: v3.0.0
          url: ${{ secrets.LOFT_ENV_URL }}
          # Specify your vCluster Platform access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
          #insecure: true

      - name: Destroy Preview Environment
        run: |
          loft delete vcluster loft-preview-${{ github.event.pull_request.number }} --project preview
