name: create-pr-preview

# on merge to main from pull request (recommended)
on:
  pull_request:
    types: [labeled]
    branches:
      - main
env:
  REPO_NAME: ${{ github.event.repository.name }}
  PR_LINK: ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}

jobs:
  create-preview-env:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      pull-requests: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - id: install-vcluster-cli
        uses: loft-sh/setup-vcluster@main
        with:
          version: v0.21.2
          url: ${{ secrets.LOFT_ENV_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
          kubectl-install: false
          kubectl-version: v1.29.2

      - id: create-preview-vcluster
        run: |
          vcluster platform create vcluster $REPO_NAME-pr-${{ github.event.pull_request.number }} --project default \
            --template preview-template \
            --link "GitHub PR=$PR_LINK" \
            --link "Preview=https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-${{ secrets.LOFT_DOMAIN }}/" \
            --link "Argo CD=https://argo.${{ secrets.LOFT_DOMAIN }}applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree"

      - id: trigger-argocd-appset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "preview-cluster-ready"

      - id: add-pr-link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: release
          message: |
            [Preview environment app link](https://${{ env.REPO_NAME}}-pr-${{ github.event.pull_request.number }}-${{ secrets.LOFT_DOMAIN }})
            
            [Argo CD App](https://argo.${{ secrets.LOFT_DOMAIN }}/applications/argocd/${{ env.REPO_NAME}}-${{ github.event.pull_request.head.ref }}-pr${{ github.event.pull_request.number }}?view=tree)
            
            [Preview vcluster pods](https://${{ secrets.LOFT_DOMAIN }}/projects/api-framework/vclusters/$REPO_NAME-pr-${{ github.event.pull_request.number }}/pods)
            
