# .github/workflows/vclusters.yaml
name: Pull Request Checks
on:
  pull_request:
    types: [labeled]
    branches:
      - "main"
jobs:
  my-app:
    if: ${{ github.event.label.name == 'preview' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
      - name: Login to vCluster Platform instance
        env:
          LOFT_URL: ${{ secrets.LOFT_ENV_URL }}
          ACCESS_KEY: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
        run: vcluster platform login $LOFT_URL --access-key $ACCESS_KEY
      - name: Create PR Virtual Cluster
        env:
          NAME: pr-${{ github.event.pull_request.number }}
        run: vcluster platform create vcluster $NAME --project default --template preview-template
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Deploy Application
        run: kubectl apply -Rf ./my-app
      - name: Wait for Deployment
        run: kubectl rollout status deployments/my-app
