name: Destroy Preview Environment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  destroy:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - id: install-vcluster-cli
        uses: loft-sh/setup-vcluster@main
        with:
          version: v0.21.2
          url: ${{ secrets.LOFT_ENV_URL }}
          # Specify your vCluster Platform access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
          #insecure: true

      - name: Destroy Preview Environment
        run: |
          vcluster platform delete vcluster vcluster-preview-${{ github.event.pull_request.number }} --project default
