name: Create Preview Environment

# Run for pull requests to our main branch
on:
  pull_request:
    branches:
      - main

# make sure the pipeline is only running once
concurrency:
  group: preview-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

# define a job that deploys the preview environment
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install vCluster CLI
        uses: loft-sh/setup-vcluster@main
        with:
          version: v0.21.2
          url: ${{ secrets.LOFT_ENV_URL }}
          # Specify your vCluster Platform access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}
          # Optional if your vCluster Platform domain certificate is insecure
          #insecure: true

      - name: Deploy Preview Environment
        run: |
          INGRESS_HOST=loft-preview-${{ github.event.pull_request.number }}.vcluster-demo.local

          # Make sure to recreate if there is an already existing environment
          vcluster platform create loft-preview-${{ github.event.pull_request.number }} --project default --recreate

          # Deploy the application here with an ingress
          helm repo add argo https://argoproj.github.io/argo-helm
          helm install argocd argo/argo-cd --version 5.16.3 \
                                            --create-namespace \
                                            -n argocd \
                                            --set server.ingress.enabled=true \
                                            --set server.ingress.hosts={$INGRESS_HOST}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ github.event.pull_request.number }}
          header: release
          message: |
            Preview environment deployed at: http://loft-preview-${{ github.event.pull_request.number }}.vcluster-demo.local
