name: create-vcluster

on:
  pull_request:
    branches:
      - main
    types: [labeled]
  
env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  create-vcluster:
    if: ${{ github.event.label.name == 'delete' }}
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - id: install-vcluster-cli
        uses: loft-sh/setup-vcluster@main
        with:
          version: v0.21.2
          url: ${{ secrets.LOFT_ENV_URL }}
          # Specify your Loft access key here
          access-key: ${{ secrets.LOFT_PREVIEW_ACCESS_KEY }}

      - id: create-vcluster
        run: |
          vcluster platform create vcluster vcluster-preview-${{ github.event.pull_request.number }} --project default --recreate
